# Change these first
owner: LimeCommerce # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: LimeCommerce Production
    url: https://limecommerce.com
    statusPageUrl: https://uptime.limecommerce.work
  - name: Staging Mebel
    url: https://mebel.limecommerce.work
    statusPageUrl: https://uptime.limecommerce.work
  - name: Staging Down
    url: https://this-site-does-not-exist.limecommerce.work
    statusPageUrl: https://uptime.limecommerce.work

notifications:
  email:
    to: akhi.young2@gmail.com
    from: heru@limecommerce.com
    smtp:
      host: smtp.gmail.com
      port: 587
      secure: false
      auth:
        user: ${{ secrets.SMTP_USERNAME_HERU }}
        pass: ${{ secrets.SMTP_PASSWORD_HERU }}

checks:
  frequency: 1 # tiap 1 menit
  retries: 1

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.limecommerce.work
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Update Down Time Notif Test - This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
