# Change these first
owner: LimeCommerce # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: LimeCommerce Production
    url: https://limecommerce.com
    icon: https://www.limecommerce.com/favicon.svg
    statusPageUrl: https://uptime.limecommerce.work
  - name: Coral Island
    url: https://coralisland.wiki/
    icon: https://coralisland.wiki/w/favicon.ico
    statusPageUrl: https://uptime.limecommerce.work

#  - name: Nihonmart Production
#    url: https://nihonmart.id/
#    icon: https://nihonmart.id/pub/media/favicon/stores/1/favicon_1.ico
#    statusPageUrl: https://uptime.limecommerce.work

notifications:
  email:
    to: ${{ secrets.NOTIFICATION_EMAIL_TO }}
    from: ${{ secrets.NOTIFICATION_EMAIL_FROM }}
    smtp:
      host: ${{ secrets.NOTIFICATION_EMAIL_SMTP_HOST }}
      port: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PORT }}
      secure: false
      auth:
        user: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
        pass: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.limecommerce.work
  faviconSvg: https://www.limecommerce.com/favicon.svg
  # light, dark, night or ocean.
  theme: light
  # baseUrl: /your-repo-name
  logoUrl: https://limecommerce.oss-ap-southeast-5.aliyuncs.com/wp-content/2022/04/logo-color.svg
  name: Uptime
  introTitle: "Welcome to the official **LimeCommerce** status page"
  introMessage: Here, you can monitor the real-time availability of our services and infrastructure. We are committed to maintaining high uptime and transparency for our clients and partners. If there are any interruptions in service, they will be reported and tracked here.
  navbar:
    - title: Status
      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
