# Change these first
owner: LimeCommerce # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: LimeCommerce Production
    url: https://limecommerce.com
    icon: https://www.limecommerce.com/favicon.svg
    statusPageUrl: https://uptime.limecommerce.work
  - name: Coral Island
    url: https://coralisland.wiki/
    icon: https://coralisland.wiki/w/favicon.ico
    statusPageUrl: https://uptime.limecommerce.work
  - name: Google
    url: https://www.google.com/
    statusPageUrl: https://uptime.limecommerce.work
  - name: Mebel
    url: https://mebel.limecommerce.work
    statusPageUrl: https://uptime.limecommerce.work

notifications:
  email:
    to: ${{ secrets.NOTIFICATION_EMAIL_TO }}
    from: ${{ secrets.NOTIFICATION_EMAIL_FROM }}
    smtp:
      host: ${{ secrets.NOTIFICATION_EMAIL_SMTP_HOST }}
      port: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PORT }}
      secure: false
      auth:
        user: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
        pass: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.limecommerce.work
  faviconSvg: https://www.limecommerce.com/favicon.svg
  metaTags:
    - name: "robots"
      content: "noindex"
  # baseUrl: /your-repo-name
  logoUrl: https://limecommerce.oss-ap-southeast-5.aliyuncs.com/wp-content/2022/04/logo-color.svg
  name: Uptime
  introTitle: "Welcome to the official **LimeCommerce** status page"
  introMessage: Here, you can monitor the real-time availability of our services and infrastructure. We are committed to maintaining high uptime and transparency for our clients and partners. If there are any interruptions in service, they will be reported and tracked here.

  js: |
    window.onload = function () {
      console.log("window.onload triggered");

      const username = prompt("Enter username:");
      const password = prompt("Enter password:");

      const encodedPassword = btoa(password);
      console.log("Username:", username);
      console.log("Encoded Password:", encodedPassword);

      // Username: admin
      // Password: 123456 → Base64: MTIzNDU2
      if (username !== "admin" || encodedPassword !== "MTIzNDU2") {
        console.log("Access denied");
        alert("Access denied");
        document.body.innerHTML =
          "<h1 style='color: red; text-align: center;'>Unauthorized</h1>";
      } else {
        console.log("Access granted");
        alert("Welcome, " + username + "!");
      }
    };

    const articles = document.querySelectorAll("article");
    let visible = false;

    function slideDown(el) {
      console.log("slideDown called on:", el);
      el.style.display = "block";
      el.style.height = "auto";
      const height = el.scrollHeight + "px";
      el.style.height = "0";
      requestAnimationFrame(() => {
        el.style.height = height;
      });
    }

    function slideUp(el) {
      console.log("slideUp called on:", el);
      el.style.height = "0";
    }

    setInterval(() => {
      console.log("Toggling articles visibility:", visible ? "hide" : "show");
      articles.forEach((article) => {
        if (visible) {
          slideUp(article);
        } else {
          slideDown(article);
        }
      });
      visible = !visible;
    }, 3000);

# navbar:
#    - title: Status
#      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
