# Change these first
owner: LimeCommerce # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: "#27654 LimeCommerce Production"
    url: https://limecommerce.com
    icon: https://www.limecommerce.com/favicon.svg
    statusPageUrl: https://uptime.limecommerce.work
    expectedStatusCodes:
      - 200
      - 201
      - 415
      - 403
      - 0
    maxResponseTime: 30000
  - name: "#86723 Coral Island"
    url: https://coralisland.wiki/
    icon: https://coralisland.wiki/w/favicon.ico
    statusPageUrl: https://uptime.limecommerce.work
    expectedStatusCodes:
      - 200
      - 201
      - 415
      - 403
    maxResponseTime: 30000
  - name: "#38492 Yamada BEST"
    url: https://yamadabestid.com
    icon: https://yamadabestid.com/media/favicon/stores/1/favicon-32x32.png
    statusPageUrl: https://uptime.limecommerce.work
    expectedStatusCodes:
      - 200
      - 201
      - 415
      - 403
    maxResponseTime: 30000
  - name: "#71530 Jade"
    url: https://jade-jakarta.com
    icon: https://jade-jakarta.com/pub/media/favicon/stores/1/favicon-jade.png
    statusPageUrl: https://uptime.limecommerce.work
    expectedStatusCodes:
      - 200
      - 201
      - 415
      - 403
    maxResponseTime: 30000
  - name: "#26981 Nihon"
    url: https://nihonmart.id
    icon: https://nihonmart.id/pub/media/favicon/stores/1/favicon_1.ico
    statusPageUrl: https://uptime.limecommerce.work
    expectedStatusCodes:
      - 200
      - 201
      - 415
      - 403
    maxResponseTime: 30000
  - name: "#54027 Rodalink"
    url: https://www.rodalink.com
    icon: https://media.rodalink.com/favicon/websites/1/favicon.png
    statusPageUrl: https://uptime.limecommerce.work
    expectedStatusCodes:
      - 200
      - 201
      - 415
      - 403
    maxResponseTime: 30000
  - name: "#19836 CNF"
    url: https://cnfstore.com
    icon: https://cnfstore.com/pub/media/favicon/stores/1/favicon.png
    statusPageUrl: https://uptime.limecommerce.work
    expectedStatusCodes:
      - 200
      - 201
      - 415
      - 403
    maxResponseTime: 30000
  - name: "#67394 Yeva"
    url: https://yeva.asia
    icon: https://yeva.asia/cdn/shop/files/Logo_Full.png
    statusPageUrl: https://uptime.limecommerce.work
    expectedStatusCodes:
      - 200
      - 201
      - 415
      - 403
    maxResponseTime: 30000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.limecommerce.work
  faviconSvg: https://www.limecommerce.com/favicon.svg
  metaTags:
    - name: "robots"
      content: "noindex"
  # baseUrl: /your-repo-name
  logoUrl: https://limecommerce.oss-ap-southeast-5.aliyuncs.com/wp-content/2022/04/logo-color.svg
  name: Uptime
  introTitle: "Welcome to the official **LimeCommerce** status page"
  introMessage: Here, you can monitor the real-time availability of our services and infrastructure. We are committed to maintaining high uptime and transparency for our clients and partners. If there are any interruptions in service, they will be reported and tracked here.

  js: |
    function removeHref() {
      document.querySelectorAll("a.logo").forEach((a) => {
        if (a.hasAttribute("href")) {
          a.removeAttribute("href");
        }
      });
    }

    document.addEventListener("DOMContentLoaded", function () {
      removeHref();
      const observer = new MutationObserver(() => {
        removeHref();
      });
      observer.observe(document.body, { childList: true, subtree: true });

      const path = window.location.pathname;
      if (path === "/history") {
        document.body.innerHTML =
          "<h1 style='color: red; text-align: center; color:#002626; margin-top: 20px'>403 Forbidden</h1>";
        return;
      }
      if (path.startsWith("/history/")) {
        return;
      }
      document.body.style.display = "none";
      const username = prompt("Enter username:");
      const password = prompt("Enter password:");
      const encodedPassword = btoa(password);
      if (username !== "lime" || encodedPassword !== "bGltZTEyMw==") {
        document.body.style.display = "block";
        document.body.innerHTML =
          "<h1 style='color: red; text-align: center; color:#002626; margin-top: 20px'>Unauthorized</h1>";
      } else {
        document.body.style.display = "block";
      }
    });

    function hidePastIncidentsSection() {
      document.querySelectorAll("section").forEach((section) => {
        const h2 = section.querySelector("h2");
        if (h2 && h2.textContent.trim() === "Past Incidents") {
          section.style.display = "none";
        }
      });
    }

    document.addEventListener("DOMContentLoaded", () => {
      hidePastIncidentsSection();
      const observer = new MutationObserver(hidePastIncidentsSection);
      observer.observe(document.body, { childList: true, subtree: true });
    });

    document.addEventListener("DOMContentLoaded", function () {
      const footer = document.querySelector("footer");
      if (footer) {
        footer.style.display = "none";
      }
    });

# navbar:
#    - title: Status
#      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
