name: Send Test Email

on:
  workflow_dispatch: # Memungkinkan dijalankan secara manual dari GitHub Actions

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
          password: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}
          subject: "[Upptime] Test Email from GitHub Actions"
          to: heru@limecommerce.com
          from: Lime <test@limecommerce.com>
          body: |
            <div className="max-w-md mx-auto bg-white font-sans">
              {/* Header */}
              <div className="bg-gray-900 text-white p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center space-x-2">
                    <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                    <span className="text-sm font-medium">UptimeRobot</span>
                  </div>
                  <a href="#" className="text-green-400 text-sm hover:underline">
                    Go to monitor →
                  </a>
                </div>
                <h1 className="text-2xl font-bold">
                  Bagasiku is <span className="text-red-500">down</span>.
                </h1>
              </div>

              {/* Content */}
              <div className="p-6 space-y-6">
                <div>
                  <p className="text-gray-700 mb-4">Hello Soma Putera,</p>
                  <p className="text-gray-700 mb-2">We just detected an incident on your monitor.</p>
                  <p className="text-gray-700 mb-4">Your service is currently down.</p>
                  <p className="text-gray-700">We will alert you when it's up again.</p>
                </div>

                {/* Monitor Details */}
                <div className="space-y-4">
                  <div>
                    <p className="text-gray-500 text-sm mb-1">Monitor name</p>
                    <p className="text-gray-900 font-medium">Bagasiku</p>
                  </div>

                  <div>
                    <p className="text-gray-500 text-sm mb-1">Checked URL</p>
                    <p className="text-gray-900 font-mono text-sm break-all">
                      https://www.bagasiku.com/
                    </p>
                  </div>

                  <div>
                    <p className="text-gray-500 text-sm mb-1">Root cause</p>
                    <p className="text-red-600 font-medium">DNS Resolving problem</p>
                  </div>

                  <div>
                    <p className="text-gray-500 text-sm mb-1">Incident started at</p>
                    <p className="text-gray-900 font-medium">2025-05-18 03:19:19</p>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex space-x-3">
                  <button className="bg-green-500 hover:bg-green-600 text-white px-6 py-3 rounded-lg font-medium text-sm transition-colors">
                    View incident details
                  </button>
                  <button className="border border-green-500 text-green-600 hover:bg-green-50 px-6 py-3 rounded-lg font-medium text-sm transition-colors">
                    Comment incident
                  </button>
                </div>
              </div>
            </div>
