name: Send Test Email

on:
  workflow_dispatch: # Memungkinkan dijalankan secara manual dari GitHub Actions

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
          password: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}
          subject: "[Upptime] Test Email from GitHub Actions"
          to: heru@limecommerce.com
          from: Lime <test@limecommerce.com>
          content_type: text/html
          body: >
            <html><body><h1 style="color:red;">Bagasiku is down</h1><p>Hello Soma Putera, your monitor is down.</p></body></html>
