name: Send Custom Email Notification

on:
  workflow_dispatch: # Bisa juga pakai schedule, atau trigger dari issue

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read email body from file
        id: read_email
        run: |
          echo "BODY<<EOF" >> $GITHUB_ENV
          cat .github/email-templates.html >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
          password: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}
          subject: "[Upptime] Custom Alert for Bagasiku"
          to: heru@limecommerce.com
          from: Lime <test@limecommerce.com>
          content_type: text/html
          body: ${{ env.BODY }}
