name: Send Custom Email Notification

on:
  workflow_dispatch: # Bisa juga pakai schedule, atau trigger dari issue

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          from-email: test@limecommerce.com
          to-email: heru@limecommerce.com
          username: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
          password: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
            <h1>This is a test email</h1>
            <p>Test Paragraph</p>
