name: Send Custom Email Notification

on:
  workflow_dispatch: # Bisa dijalankan manual dari GitHub UI

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email with HTML content
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
          password: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}
          subject: "⚠️ Uptime Alert"
          to: heru@limecommerce.com
          from: Lime Uptime <test@limecommerce.com>
          content_type: text/html
          body: |
            <h1>🚨 Website Down</h1>
            <p><strong>https://limecommerce.com</strong> is currently <span style="color:red;">down</span>.</p>
            <p>Please check the issue immediately.</p>
