name: Send Custom Email Notification

on:
  workflow_dispatch: # Bisa dijalankan manual dari GitHub UI

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Send email with HTML content
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.NOTIFICATION_EMAIL_SMTP_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: heru@limecommerce.com
          # Required sender full name (address can be skipped):
          from: Lime Uptime <test@limecommerce.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://README.html
