name: Send Custom Email Notification
on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTML Email
        uses: mattnotmitt/send-email@v1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
          password: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}
          subject: ⚠️ Uptime Alert: Website Down
          to: heru@limecommerce.com
          from: test@limecommerce.com
          content_type: text/html
          body: |
            <html>
              <body>
                <h1 style="color: red;">🚨 Website Down Alert</h1>
                <p>Dear team,</p>
                <p><strong>https://limecommerce.com</strong> is currently <span style="color: red;">down</span>.</p>
                <p>Please investigate as soon as possible.</p>
                <hr />
                <small>This is an automated email from GitHub Actions - Upptime</small>
              </body>
            </html>