name: Send Test Email

on:
  workflow_dispatch: # Memungkinkan dijalankan secara manual dari GitHub Actions

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.NOTIFICATION_EMAIL_SMTP_USERNAME }}
          password: ${{ secrets.NOTIFICATION_EMAIL_SMTP_PASSWORD }}
          subject: "[Upptime] Test Email from GitHub Actions"
          to: heru@limecommerce.com
          from: Lime <test@limecommerce.com>
          content_type: text/html
          body: >
            <table width="100%" cellpadding="0" cellspacing="0" style="font-family: sans-serif; background-color: #f4f4f4; padding: 20px;">
              <tr>
                <td align="center">
                  <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; overflow: hidden;">
                    <!-- Header -->
                    <tr>
                      <td style="background-color: #1f2937; color: #ffffff; padding: 24px;">
                        <table width="100%">
                          <tr>
                            <td style="font-size: 14px;">
                              <span style="display: inline-block; width: 10px; height: 10px; background-color: #22c55e; border-radius: 50%; margin-right: 8px;"></span>
                              UptimeRobot
                            </td>
                            <td align="right" style="font-size: 14px;">
                              <a href="#" style="color: #4ade80; text-decoration: none;">Go to monitor →</a>
                            </td>
                          </tr>
                          <tr>
                            <td colspan="2" style="padding-top: 16px;">
                              <h1 style="font-size: 24px; margin: 0;">Bagasiku is <span style="color: #ef4444;">down</span>.</h1>
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>

                    <!-- Body -->
                    <tr>
                      <td style="padding: 24px; color: #374151;">
                        <p>Hello Soma Putera,</p>
                        <p>We just detected an incident on your monitor.</p>
                        <p>Your service is currently down.</p>
                        <p>We will alert you when it's up again.</p>

                        <!-- Monitor Info -->
                        <table width="100%" style="margin-top: 24px;">
                          <tr>
                            <td style="color: #6b7280; font-size: 12px;">Monitor name</td>
                          </tr>
                          <tr>
                            <td style="font-weight: bold; padding-bottom: 12px;">Bagasiku</td>
                          </tr>
                          <tr>
                            <td style="color: #6b7280; font-size: 12px;">Checked URL</td>
                          </tr>
                          <tr>
                            <td style="font-family: monospace; font-size: 14px; padding-bottom: 12px;">https://www.bagasiku.com/</td>
                          </tr>
                          <tr>
                            <td style="color: #6b7280; font-size: 12px;">Root cause</td>
                          </tr>
                          <tr>
                            <td style="color: #dc2626; font-weight: bold; padding-bottom: 12px;">DNS Resolving problem</td>
                          </tr>
                          <tr>
                            <td style="color: #6b7280; font-size: 12px;">Incident started at</td>
                          </tr>
                          <tr>
                            <td style="font-weight: bold;">2025-05-18 03:19:19</td>
                          </tr>
                        </table>

                        <!-- Buttons -->
                        <table width="100%" style="margin-top: 24px;">
                          <tr>
                            <td>
                              <a href="#" style="display: inline-block; background-color: #22c55e; color: #ffffff; text-decoration: none; padding: 12px 20px; border-radius: 6px; font-size: 14px; margin-right: 10px;">
                                View incident details
                              </a>
                              <a href="#" style="display: inline-block; border: 1px solid #22c55e; color: #22c55e; text-decoration: none; padding: 12px 20px; border-radius: 6px; font-size: 14px;">
                                Comment incident
                              </a>
                            </td>
                          </tr>
                        </table>

                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
